name: Release

on:
  push:
    tags: [ "*" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Set up Poetry
      run: |
        python -m pip install poetry
    - name: Install dependencies
      run: |
        poetry install
    - name: Build
      run: |
        poetry build
    - name: Mint token
      id: mint
      uses: tschm/token-mint-action@v1.0.2
    - name: Publish
      run: |
        poetry publish -u __token__ -p '${{ steps.mint.outputs.api-token}}'